server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customerservice
          predicates:
            - Path=/customer/**
        - id: photo-serivce
          uri: lb://photo-service
          predicates:
            - Path=/foto/**
        